---
title: "SA_pipe"
author: "Fiona Spooner"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r Sourcing}
source(here::here("combine/FS","pat.R"))
source("SA_pipeline_functions.R")

```


```{r Libraries}
#devtools::install_github("https://github.com/hferg/sdmpl", auth_token = GITHUB_PAT)

library(dplyr)
library(raster)
library(sdmpl)
library(sf)
```

# Data Preparation 

We are only interested in species that occur in southern Africa, here defined as locations below the equator on the African continent. 

```{r Data preparation - setting extent}

xmin <- 4
xmax <- 59 # could be 52 if we don't want to include Mauritius 
ymin <- -35
ymax <- 0

ext<-extent(xmin, xmax, ymin, ymax)

```


Removing species we aren't interested in e.g. fish.
```{r List of Species - gathered from SANBI}
gbif_all <- read.csv("D:/Fiona/SHEFS/GBIF/Species_List/All_GBIF_Species_List.csv", stringsAsFactors = FALSE)

g_sp <- gbif_all %>% 
  dplyr::select(kingdom, phylum, class, order, family, genus, species) %>% 
  filter(!is.na(species) & (kingdom == "Animalia"| kingdom == "Plantae") & (phylum == "Arthrpoda" | phylum == "Chordata" | phylum == "Tracheophyta" ) & (class != "Actinopterygii" & class != "Elasmobranchii")) %>% 
  distinct()

```


```{r}
sanbi_all <- 
  do.call(rbind,
          lapply(list.files(path = "D:/Fiona/SHEFS/SANBI/Species_List", pattern = "*.csv", full.names = TRUE), read.csv))

s_sp <- na.omit(unique(as.character(sanbi_all$Binomial)))

s_sp<-s_sp[!s_sp %in% g_sp]


``` 

Get the taxonomy of the species gathered from SANBI 

```{r}

tr_out<-lapply(s_sp[1:10], tax_out)

san_df<-do.call(rbind, tr_out)

all_sp<-rbind(g_sp, san_df)

```

```{r Downloading data from GBIF}

gbifData(all_sp$species[1], ext = ext)

spxy_out<-lapply(s_sp[1:4], gbifData, ext = ext)

```



##Coordinate Cleaner
```{r}

```

###Rarefy Points
```{r}


```


###Environmental Data Prep
```{r}


```

###Extract Data
```{r}

```


###Background Data
```{r}

ecoreg <-
  st_read(here::here("WWF_Ecoregions/official/wwf_terr_ecos.shp"))

ecoreg <- ecoreg %>%
  select(OBJECTID, ECO_NAME)   ##just selecting out the columns we're interested in

occ_files <-
  list.files(
    here::here("GBIF/Occurences/Network_Groups/"),
    pattern = "*.csv",
    full.names = TRUE,
    recursive = TRUE
  )


background_sampler <- function(occ_file, no_pnts) {
  sf_int <- read_csv(occ_file) %>%
    dplyr::select("decimalLongitude", "decimalLatitude") %>%
    distinct() %>%
    st_as_sf(.,
             coords = c("decimalLongitude", "decimalLatitude"),
             crs = 4326) %>%
    st_intersection(., ecoreg)
  
  bkg_ecoreg <- ecoreg %>%
    filter(ECO_NAME %in% sf_int$ECO_NAME) %>%
    st_sample(., size = no_pnts, type = "random")
  
  print(basename(occ_file))
  return(bkg_ecoreg)
}




```

###Fit Models
```{r}


```


